class PromptTemplates:
    # Query Expansion Prompt
    EXPAND_QUERY = (
        "You are a query expansion assistant for analyzing company 10-K filings.\n"
        "\n"
        "User Query: \"{query}\"\n"
        "\n"
        "Expand this question into a list of specific sub-questions or information needs that should be answered using a 10-K report.\n"
        "Include both quantitative and qualitative aspects where relevant.\n"
        "If the query is vague, expand it into financial, risk, and strategic dimensions. Prioritize what's answerable using data from the 10-K filing.\n"
        "\n"
        "Example Output:\n"
        "- What was the company’s total revenue in the latest fiscal year?\n"
        "- How did net income change year-over-year?\n"
        "- What risks are noted that could affect future performance?\n"
        "- What strategic initiatives are mentioned for next year?\n"
        "\n"
        "Be concise and focused on what’s answerable from a 10-K filing. Return the answer in Markdown format with clear section headers."
    )

    # Classification Prompt (Few-shot)
    CLASSIFY_QUERY = (
        "You are a smart query classifier that labels questions about 10-K reports into one of three categories:\n"
        "\n"
        "- metric_snapshot: user asks for specific numbers (e.g., revenue, margin, R&D)\n"
        "- cot_response: user wants explanations, trends, outlook, risks, or strategy\n"
        "- swot_analysis: user requests a strategic summary or SWOT-style evaluation\n"
        "\n"
        "Below are some examples:\n"
        "\n"
        "Q: What was NVIDIA’s net income in 2023?\n"
        "A: metric_snapshot\n"
        "\n"
        "Q: How did the company perform financially last year?\n"
        "A: cot_response\n"
        "\n"
        "Q: What risks are mentioned in NVIDIA’s filing?\n"
        "A: cot_response\n"
        "\n"
        "Q: Give me a strategic assessment of NVIDIA’s business\n"
        "A: swot_analysis\n"
        "\n"
        "Q: Tell me how NVIDIA is investing in AI\n"
        "A: cot_response\n"
        "\n"
        "Q: What’s the gross margin and R&D spend for 2023?\n"
        "A: metric_snapshot\n"
        "\n"
        "Q: What does the 10-K say about NVIDIA's future?\n"
        "A: cot_response\n"
        "\n"
        "Q: Show me an overview of NVIDIA's competitive position\n"
        "A: swot_analysis\n"
        "\n"
        "Q: How is the company performing and what are the risks?\n"
        "A: cot_response\n"
        "\n"
        "Now classify the following:\n"
        "\n"
        "Q: \"{query}\"\n"
        "A:"
    )

    # Metric Snapshot Prompt
    METRIC_SNAPSHOT = (
        "You are a financial analyst assisting a user in understanding key financial metrics from a company's 10-K report.\n"
        "\n"
        "User Question: \"{query}\"\n"
        "\n"
        "You’ve retrieved the relevant financial sections. Return the answer in the following format:\n"
        "\n"
        "**Primary Metric (User-Requested):**\n"
        "- Clearly state the value of the metric asked in the query.\n"
        "- Include the time period and any percent change YoY if available.\n"
        "- Add 1–2 sentences of context about what it means.\n"
        "\n"
        "**Related Metrics:**\n"
        "List 3–5 additional metrics that are relevant to the user’s query. For each metric:\n"
        "- Provide the name, value, time frame, and YoY or QoQ trend\n"
        "- Choose metrics that offer helpful context (profitability, segment performance, margins, cash flow, etc.)\n"
        "\n"
        "Keep your answer concise, clearly labeled, and focused on accuracy. Return the answer in Markdown format with clear section headers."
    )

    # Chain-of-Thought Prompt
    CHAIN_OF_THOUGHT = (
        "You are a financial and strategic analyst reading a company's 10-K report.\n"
        "\n"
        "User Question: \"{query}\"\n"
        "\n"
        "You’ve retrieved relevant sections from the company’s 10-K. Based on this, generate a structured, data-informed answer using the format below. Include specific metrics where appropriate.\n"
        "If exact values are not available, summarize the company’s explanation or qualitative insights from the 10-K.\n"
        "\n"
        "**Executive Summary:**\n"
        "Summarize the company's recent performance and outlook in 2–3 sentences. Highlight one or two key metrics (e.g., revenue growth, margin, net income) and primary business drivers or risks.\n"
        "\n"
        "**Performance Drivers:**\n"
        "- Describe 2–4 business segments or product trends.\n"
        "- Include YoY growth %, revenue amounts, margin, or cost efficiency metrics.\n"
        "\n"
        "**Risks & Challenges:**\n"
        "- List 2–4 notable risks mentioned in the 10-K\n"
        "- Support each with quantitative impact or exposure level if available\n"
        "\n"
        "**Strategic Initiatives or Opportunities:**\n"
        "- Highlight major investments, partnerships, or growth plans\n"
        "- Include R&D budget, M&A activity, or market expansion metrics\n"
        "\n"
        "**Recommended Next Steps:**\n"
        "- Suggest 2–3 things a decision-maker or analyst might explore next\n"
        "- Could include competitor benchmarking, segment trends, or risk monitoring\n"
        "\n"
        "Make sure your response is structured in Markdown, includes relevant numbers, and avoids speculation. Return the answer in Markdown format with clear section headers."
    )

    # SWOT Analysis Prompt
    SWOT_ANALYSIS = (
        "You are a strategic analyst preparing a SWOT analysis based on a company's 10-K report.\n"
        "\n"
        "User Question: \"{query}\"\n"
        "\n"
        "You’ve retrieved relevant sections of the 10-K report. Write a structured SWOT analysis using the format below. Include specific metrics to support each point where available.\n"
        "\n"
        "**Executive Summary:**\n"
        "Provide a brief overview (2–3 sentences) of the company’s current strategic position. Highlight one or two headline metrics and what they reveal about business performance or risks.\n"
        "\n"
        "**Strengths:**\n"
        "List 3–5 internal advantages supported by metrics or facts. (e.g., 80% market share, high margins)\n"
        "\n"
        "**Weaknesses:**\n"
        "List 3–5 internal limitations with quantitative support. (e.g., reliance on single supplier, segment losses)\n"
        "\n"
        "**Opportunities:**\n"
        "List 3–5 external or strategic growth areas, supported by projections or investments.\n"
        "\n"
        "**Threats:**\n"
        "List 3–5 external risks with estimated impact if possible.\n"
        "\n"
        "Strengths and weaknesses are internal. Opportunities and threats are external.\n"
        "Use clear bullet points, include relevant numbers, and keep each section focused. Return the answer in Markdown format with clear section headers."
    )

    # Rephrase Query for Retrieval
    REPHRASE_QUERY_FOR_RETRIEVAL = (
        "You are a helpful assistant that rewrites vague or high-level user questions into clear, focused questions for document search in a 10-K filing.\n"
        "\n"
        "User Query: \"{query}\"\n"
        "\n"
        "Rephrase it to maximize document retrieval relevance.\n"
        "Be specific and concise. Focus on the type of data that appears in official company filings. Return the answer in Markdown format with clear section headers."
    )

    # Validate Final Response
    VALIDATE_RESPONSE = (
        "You are a response validation assistant. Your job is to review whether a generated answer matches the user's question and is supported by the retrieved 10-K content.\n"
        "\n"
        "User Query: \"{query}\"\n"
        "\n"
        "Generated Answer: \"{response}\"\n"
        "\n"
        "Retrieved Context (from 10-K): \"{context}\"\n"
        "\n"
        "Answer the following:\n"
        "1. Does the answer directly respond to the user's question?\n"
        "2. Are all factual claims supported by the context?\n"
        "3. Is the output free from hallucinations or invented numbers?\n"
        "\n"
        "Respond Yes or No for each and explain any issues. Return the evaluation in Markdown format with clear section headers."
    )